#!/bin/csh -f
# 1
# 0
# 1
#  1.08070779
#  0.13316862
# 1
#high res
#       5
# 5
# 1
# 1
#default
# 10.00000000
#default
#  5.00000000
# 92.00000000
#    1
#    1
# Now begin csh commands.
unalias m
unalias s
unalias w
alias s "show -s nirspecsim"
alias m "modify -s nirspecsim"
alias w "waitfor -s nirspecsim"
